### ISSUE TITLE
Fix issue #42

### ISSUE THREAD

**Issue by ghiocgeorge** [ghiocgeorge/Don-t-forget-v2#45]
you shouldn't hardcode this number 5. you should have an app config, that tell you this kind of information. do you understand what I mean by app config?

_Originally posted by @andreisamoila74 in https://github.com/ghiocgeorge/Don-t-forget-v2/pull/42#discussion_r579772265_

@ghiocgeorge 
Hmm, no, I didn't understand why I need this if for now, the users can't change this number of days, and also, isn't very clear what you want to say with this app config. Maybe to create a new field in Item Model, where I saved this info, to be easy to make a new future for users in the future? Or when you say "app config" you refer to a centralized place like application.proprieties for Spring Boot, and the info to be taken from there? Please tell me if I understood and which approach is the best for now. Thank you!

@andreisamoila74 
something like a centralized configuration menu for admins. to set thing like this.
it's a table in the database that contains different info for some global settings in your app

@ghiocgeorge
Ok. Now I think I understood. I will create an issue for this task. Thank you.

**Comment by andreisamoila74** [comment]
remember to change the name of the the issue
